<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAorxrld\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAorxrld/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAorxrld.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAorxrld\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAorxrld\App_KernelDevDebugContainer([
    'container.build_hash' => 'Aorxrld',
    'container.build_id' => 'd3ac896c',
    'container.build_time' => 1606405081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAorxrld');
